name: tex_to_pdf
on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Generate PDF document
        uses: hspaans/latexmk-action@v2.1.0
        with:
          format: pdf
          filename: antrag.tex
          options: -shell-escape
